trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: certifyacrpmwst7bkkpgrc
  imageName: certify-api
  containerAppName: certify-api
  resourceGroup: RG-Josef-Al-Husseini-e0aa81-DotNetCloudDeveloper-VT-Mars-Goteborg

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build API'
    inputs:
      command: build
      projects: 'src/Api/Api.csproj'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: test
      projects: '**/*Tests.csproj'